name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        compiler: [gcc, clang]
        buildtool: [autotools, distcheck, cmake]
        exclude:
        - os: macos-10.15
          buildtool: distcheck
        - compiler: gcc
          buildtool: distcheck

    steps:
    - uses: actions/checkout@v3
    - name: Linux setup
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install \
          g++-8 \
          autoconf \
          automake \
          autotools-dev \
          libtool \
          pkg-config \
          libcunit1-dev \
          cmake \
          cmake-data
    - name: MacOS setup
      if: runner.os == 'macOS'
      run: |
        brew install cunit autoconf automake pkg-config libtool
    - name: Setup clang
      if: matrix.compiler == 'clang'
      run: |
        echo 'CC=clang' >> $GITHUB_ENV
        echo 'CXX=clang++' >> $GITHUB_ENV
    - name: Setup gcc
      if: runner.os == 'Linux' && matrix.compiler == 'gcc'
      run: |
        echo 'CC=gcc-8' >> $GITHUB_ENV
        echo 'CXX=g++-8' >> $GITHUB_ENV
    - name: Configure autotools
      if: matrix.buildtool == 'autotools'
      run: |
        autoreconf -i && ./configure --enable-werror
    - name: Configure distcheck
      if: matrix.buildtool == 'distcheck'
      run: |
        autoreconf -i && ./configure
    - name: Configure cmake
      if: matrix.buildtool == 'cmake'
      run: |
        autoreconf -i && ./configure
        make dist

        VERSION=$(grep PACKAGE_VERSION config.h | cut -d' ' -f3 | tr -d '"')
        tar xf nghttp3-$VERSION.tar.gz
        cd nghttp3-$VERSION
        mkdir build
        cd build

        echo 'NGHTTP3_BUILD_DIR='"$PWD" >> $GITHUB_ENV

        cmake $CMAKE_OPTS ..
    - name: Build nghttp3
      if: matrix.buildtool != 'distcheck'
      run: |
        [ -n "$NGHTTP3_BUILD_DIR" ] && cd "$NGHTTP3_BUILD_DIR"
        make
        make check
    - name: Build nghttp3 with distcheck
      if: matrix.buildtool == 'distcheck'
      run: |
        make distcheck
